### ISSUE TITLE
Bug in EPUBcfi.Generator.generateDocumentRangeComponent and EPUBcfi.Interpreter.getTargetElement

### ISSUE THREAD

**Issue by hrishikesh-kadam** [readium/readium-cfi-js#74]
#### Expected Behaviour
[Issue 2.zip](https://github.com/readium/readium-cfi-js/files/2721033/Issue.2.zip)
In above zip, open ch01.xhtml and select text "ess" from `<b>accessible data</b>` in 1st para.
Then click 'c' from the keyboard, which would run getSelectionCfi() in highlight.js
getSelectionCfi() tries to get the CFI from selection `range`

Expected behavior is that it should generate following CFI - 
`/4/2[introduction]/4/4,/1:3,/1:6`

#### Observed behaviour
Instead, it generates - 
`/4/2[introduction]/4/2,/1:3,/1:6`

#### Steps to reproduce
Explained above

#### Test file(s)
[Issue 2.zip](https://github.com/readium/readium-cfi-js/files/2721033/Issue.2.zip)

master/readium-cfi.umd.js - https://github.com/readium/readium-cfi-js/blob/aa416f064e3780a3c51ac02aea7b496a31818c3e/dist/readium-cfi.umd.js
develop/readium-cfi.umd.js - https://github.com/readium/readium-cfi-js/blob/9c7e74634d84e0f9fdf46631bb5369535286d0f0/dist/readium-cfi.umd.js

### Product
Other - Trying to use CFI for highlight feature in FolioReader-Android

#### Additional information

Also, there seems to be a bug in `EPUBcfi.Interpreter.getTargetElement()`
By clicking 't' on the keyboard, test() from highlight.js gets invoked which tries to get the target element  from CFI `epubcfi(/0!/4/2[introduction]/4/4` but following exception is thrown - 

```javascript
Uncaught OutOfRangeError: Error
    at elementNodeStep (/Issue%202/develop/readium-cfi.umd.js:10862:12)
    at followIndexStep (/Issue%202/develop/readium-cfi.umd.js:10989:20)
    at interpretIndexStepNode (/Issue%202/develop/readium-cfi.umd.js:12782:22)
    at interpretLocalPath (/Issue%202/develop/readium-cfi.umd.js:12849:23)
    at Object.getTargetElement (/Issue%202/develop/readium-cfi.umd.js:12989:11)
    at test (/Issue%202/highlight.js:35:36)
    at XMLDocument.onKeyPressed (/Issue%202/highlight.js:18:13)
```

Expected behavior would be to get `<b>accessible data</b>` element from 1st para.

**Comment by hrishikesh-kadam** [comment]
Sorry, my bad. This doesn't seem to be a bug.
Thank you for this awesome library.
